apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2","version":"assembling-app-server_release-tencentyun_85dd3f8e"},"labels":{"run":"assembling-app-server"},"name":"assembling-app-server","namespace":"default"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":2,"revisionHistoryLimit":2147483647,"selector":{"matchLabels":{"run":"assembling-app-server"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"assembling-app-server"}},"spec":{"containers":[{"env":[{"name":"APPNAME","value":"assembling-app-server"},{"name":"APPPORT","value":"8080"},{"name":"APPIP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}}],"envFrom":[{"configMapRef":{"name":"springcloud-env"}}],"image":"ccr.ccs.tencentyun.com/carconnect/eureka_tool:0.2","imagePullPolicy":"Always","name":"eureka-sidecar","resources":{"requests":{"cpu":"250m","memory":"500Mi"}},"securityContext":{"privileged":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"env":[{"name":"APPNAME","value":"assembling-app-server"},{"name":"PUBLIC_NAME","value":"appserver"},{"name":"CONFIG_NAME","value":"app-server"}],"image":"ccr.ccs.tencentyun.com/carconnect/appserver:1.2.52-20190327.072646-1","imagePullPolicy":"Always","name":"assembling-app-server","resources":{"requests":{"cpu":"250m","memory":"2Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/timafawvw/config/app-server","name":"app-server","readOnly":true}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"qcloudregistrykey"},{"name":"tencenthubkey"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"app-server","secret":{"defaultMode":420,"secretName":"assembling-app-server"}}]}}}}
    version: assembling-app-server_release-tencentyun_85dd3f8e
  creationTimestamp: "2020-07-26T14:50:48Z"
  generation: 2
  labels:
    run: assembling-app-server
  name: assembling-app-server
  namespace: default
  resourceVersion: "2190381740"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/assembling-app-server
  uid: 37da2078-a3dd-41c8-8a59-c4cad43b989e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      run: assembling-app-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: assembling-app-server
    spec:
      containers:
      - env:
        - name: APPNAME
          value: assembling-app-server
        - name: APPPORT
          value: "8080"
        - name: APPIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: springcloud-env
        image: ccr.ccs.tencentyun.com/carconnect/eureka_tool:0.2
        imagePullPolicy: Always
        name: eureka-sidecar
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: APPNAME
          value: assembling-app-server
        - name: PUBLIC_NAME
          value: appserver
        - name: CONFIG_NAME
          value: app-server
        image: ccr.ccs.tencentyun.com/carconnect/appserver:1.2.52-20190327.072646-1
        imagePullPolicy: Always
        name: assembling-app-server
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /timafawvw/config/app-server
          name: app-server
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: app-server
        secret:
          defaultMode: 420
          secretName: assembling-app-server
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-07-28T07:47:39Z"
    lastUpdateTime: "2020-07-28T07:47:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
